broker_ip: "192.168.86.82"
port: 8883
client_name: client-rpi400
ca_certs: 
- /etc/mosquitto/certs/ca.crt
certfile: /etc/mosquitto/certs/client-rpi400.crt
keyfile: /etc/mosquitto/certs/client-rpi400.key